### ISSUE TITLE
ERROR: Error occurred in poll cycle: undefined method `empty?' for #<URI::Generic:>

### ISSUE THREAD

**Issue by rainmanh** [gingerlime/graphite-newrelic#1]
Hi

For some reason I cannot get the data collection running.
My configuration file is as follows:

``` newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'nerelic_key'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1
#
# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  graphite:
    settings:
      server: 
       url: 'http://127.0.0.1'
        # username and password if necessary for basic authentication
       #username: graphite
       #password: password
      targets:
        - 
          target: 'stats.dashboard.test'
          from: '-180min'
          units: '%'
```

If I try to reach http://127.0.0.1 graphites responds and I do not have security set at that level.
Also the target exists as I have run a request such us:
curl http://localhost/render/?target=stats.dashboard.test

Any idea?

Thanks

**Comment by gingerlime** [comment]
Hi,

Unfortunately I don't use Newrelic or this plugin any more. I was mostly playing-around just testing the idea. Last time I used it was way over a year ago... It's hard for me to say what might go wrong in your case. Did you set the `GUID` as explained on the [usage](https://github.com/gingerlime/graphite-newrelic#usage) section?

**Comment by rainmanh** [comment]
Hi

The issue was Ruby version related. So it would not work with 1.8.X unless some extensive changes happen around.
So, it works now after upgrading ruby.

Thanks!
